[project]
name = "Bookworms-n-Bestsellers"
version = "1.0.0"
description = "A Library of sorts, to get customised recommendations and a platform to exchange your books."
dependencies = [
    "flask",
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"