"""empty message

Revision ID: 13a6441be883
Revises: cbc4d3c9489d
Create Date: 2024-06-24 20:13:12.788235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13a6441be883'
down_revision = 'cbc4d3c9489d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mOwner', sa.Integer(), nullable=False))
        batch_op.drop_constraint('fk_messages_requesteeId_users', type_='foreignkey')
        batch_op.drop_constraint('fk_messages_requesterId_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_messages_mOwner_users'), 'users', ['mOwner'], ['uId'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_messages_mOwner_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_messages_requesterId_users', 'users', ['requesterId'], ['uId'])
        batch_op.create_foreign_key('fk_messages_requesteeId_users', 'users', ['requesteeId'], ['uId'])
        batch_op.drop_column('mOwner')

    # ### end Alembic commands ###
