"""Added Server Stats, and m:n relationship

Revision ID: 3b6e32af2b12
Revises: c725e746f8eb
Create Date: 2024-05-22 00:43:54.997816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b6e32af2b12'
down_revision = 'c725e746f8eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('server_stats',
    sa.Column('sId', sa.Integer(), nullable=False),
    sa.Column('books_exchanged', sa.Integer(), nullable=False),
    sa.Column('number_of_users', sa.Integer(), nullable=False),
    sa.Column('books_available', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('sId')
    )
    op.create_table('user_messages',
    sa.Column('uId', sa.Integer(), nullable=False),
    sa.Column('mId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mId'], ['messages.mId'], ),
    sa.ForeignKeyConstraint(['uId'], ['users.uId'], ),
    sa.PrimaryKeyConstraint('uId', 'mId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_messages')
    op.drop_table('server_stats')
    # ### end Alembic commands ###
