"""empty message

Revision ID: c725e746f8eb
Revises: 
Create Date: 2024-05-22 00:00:11.195214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c725e746f8eb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('bId', sa.Integer(), nullable=False),
    sa.Column('ISBN', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('genre', sa.String(length=50), nullable=True),
    sa.Column('avg_rating', sa.Float(), nullable=False),
    sa.Column('author', sa.String(length=50), nullable=False),
    sa.Column('imgUrlSmall', sa.String(length=250), nullable=True),
    sa.Column('imgUrlLarge', sa.String(length=250), nullable=True),
    sa.Column('year_of_publication', sa.String(length=50), nullable=False),
    sa.Column('publisher', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('bId'),
    sa.UniqueConstraint('ISBN')
    )
    op.create_table('users',
    sa.Column('uId', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=50), nullable=False),
    sa.Column('location', sa.String(length=50), nullable=False),
    sa.Column('login_type', sa.String(length=50), nullable=False),
    sa.Column('contact_no', sa.String(length=50), nullable=False),
    sa.Column('books_rated', sa.Integer(), nullable=False),
    sa.Column('date_joined', sa.Date(), nullable=False),
    sa.Column('exchanges_made', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('uId'),
    sa.UniqueConstraint('email')
    )
    op.create_table('exchanges',
    sa.Column('eId', sa.Integer(), nullable=False),
    sa.Column('uId', sa.Integer(), nullable=False),
    sa.Column('bId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bId'], ['books.bId'], ),
    sa.ForeignKeyConstraint(['uId'], ['users.uId'], ),
    sa.PrimaryKeyConstraint('eId')
    )
    op.create_table('ratings',
    sa.Column('rId', sa.Integer(), nullable=False),
    sa.Column('uId', sa.Integer(), nullable=False),
    sa.Column('bId', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['bId'], ['books.bId'], ),
    sa.ForeignKeyConstraint(['uId'], ['users.uId'], ),
    sa.PrimaryKeyConstraint('rId')
    )
    op.create_table('trainablebooks',
    sa.Column('tId', sa.Integer(), nullable=False),
    sa.Column('uId', sa.Integer(), nullable=False),
    sa.Column('bId', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['bId'], ['books.bId'], ),
    sa.ForeignKeyConstraint(['uId'], ['users.uId'], ),
    sa.PrimaryKeyConstraint('tId')
    )
    op.create_table('messages',
    sa.Column('mId', sa.Integer(), nullable=False),
    sa.Column('requestFor', sa.Integer(), nullable=False),
    sa.Column('inReturnFor', sa.Integer(), nullable=False),
    sa.Column('requesterId', sa.Integer(), nullable=False),
    sa.Column('requesteeId', sa.Integer(), nullable=False),
    sa.Column('currentState', sa.String(length=50), nullable=False),
    sa.Column('message', sa.String(length=250), nullable=False),
    sa.Column('eId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['eId'], ['exchanges.eId'], ),
    sa.ForeignKeyConstraint(['inReturnFor'], ['books.bId'], ),
    sa.ForeignKeyConstraint(['requestFor'], ['books.bId'], ),
    sa.ForeignKeyConstraint(['requesteeId'], ['users.uId'], ),
    sa.ForeignKeyConstraint(['requesterId'], ['users.uId'], ),
    sa.PrimaryKeyConstraint('mId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_table('trainablebooks')
    op.drop_table('ratings')
    op.drop_table('exchanges')
    op.drop_table('users')
    op.drop_table('books')
    # ### end Alembic commands ###
